In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]
np.array([my_list])

array([[1, 2, 3]])

In [3]:
my_matrix=[[1,2,3],[4,5,6]]

In [4]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [11]:
np.linspace(0,4,21)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. ])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.randn(10,3)

array([[-0.60661243,  0.10934675,  0.67352586],
       [ 0.49915758,  0.60532339, -1.9262003 ],
       [-1.07179418,  0.141219  ,  0.1191976 ],
       [ 0.58337838,  0.81262553, -0.23367169],
       [-0.40601124, -0.9520117 ,  0.14732253],
       [-0.69555564,  1.62326636, -1.28097107],
       [ 1.05698113,  0.29411822,  0.01402552],
       [ 0.56987972,  0.38295093,  1.00510661],
       [ 0.08427812,  1.17595678, -1.85476379],
       [ 0.98071591, -0.01474233, -1.04276904]])

In [25]:
np.random.seed(42)
np.random.randint(0,101,5)

array([51, 92, 14, 71, 60], dtype=int32)

In [24]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

le seed permet de definir un ensemble de nombre aléatoires

In [26]:
arr = np.arange (0,25)

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr= np.random.randint(0,101,10)

In [29]:
ranarr.max()

np.int32(99)

In [31]:
ranarr.dtype

dtype('int32')

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr.argmin()

np.int64(8)

In [34]:
arr= arr.reshape(5,5)

In [35]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [38]:
ar=np.arange(0,11)

In [33]:
arr.shape

(25,)

In [39]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
ar[1:5]

array([1, 2, 3, 4])

In [41]:
ar[:5]

array([0, 1, 2, 3, 4])

In [42]:
ar[0:5]=100

In [43]:
ar

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
ar=np.arange(0,11)

In [46]:
slice_of_ar

NameError: name 'slice_of_ar' is not defined

In [47]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
ar_2d=np.random.randint

In [51]:
ar_2d

<bound method RandomState.randint of RandomState(MT19937) at 0x26A6C1C1A40>

In [52]:
ar_2d[2]

TypeError: 'method' object is not subscriptable

In [54]:
ar[ar>4]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
ar/ar

C:\Users\jeanc\AppData\Local\Temp\ipykernel_45968\2192729293.py:1: RuntimeWarning: invalid value encountered in divide
  ar/ar


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [59]:
np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [60]:
ar.sum

<function ndarray.sum>

In [61]:
ar.var

<function ndarray.var>

In [64]:
ard= np.arange(0,25,).reshape(5,5)

In [66]:
ard.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [67]:
np.ones

<function numpy.ones(shape, dtype=None, order='C', *, device=None, like=None)>